hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  cat_features:
  - person_attribute_a_1
  - person_attribute_b
  - person_prefer_c
  - person_prefer_d_1
  - person_prefer_d_2
  - person_prefer_d_3
  - person_prefer_e
  - person_prefer_h_1
  - person_prefer_h_2
  - person_prefer_h_3
  - contents_attribute_i
  - contents_attribute_a
  - contents_attribute_j_1
  - contents_attribute_c
  - contents_attribute_l
  - contents_attribute_d
  - contents_attribute_m
  - contents_attribute_e
  - contents_attribute_h
  - person_rn
  - person_prefer_d_1_attribute_d_d
  - person_prefer_d_1_attribute_d_s
  - person_prefer_d_1_attribute_d_m
  - person_prefer_d_1_attribute_d_l
  - person_prefer_d_2_attribute_d_d
  - person_prefer_d_2_attribute_d_s
  - person_prefer_d_2_attribute_d_m
  - person_prefer_d_2_attribute_d_l
  - person_prefer_d_3_attribute_d_d
  - person_prefer_d_3_attribute_d_s
  - person_prefer_d_3_attribute_d_m
  - person_prefer_d_3_attribute_d_l
  - contents_attribute_d_attribute_d_d
  - contents_attribute_d_attribute_d_s
  - contents_attribute_d_attribute_d_m
  - contents_attribute_d_attribute_d_l
  - person_prefer_h_1_attribute_h_p
  - person_prefer_h_2_attribute_h_p
  - person_prefer_h_3_attribute_h_p
  - contents_attribute_h_attribute_h_p
  - contents_attribute_l_attribute_l_d
  - contents_attribute_l_attribute_l_s
  - contents_attribute_l_attribute_l_m
  - contents_attribute_l_attribute_l_l
  path: ../input/jobcare-recommendation
  submit: sample_submission.csv
  test: test.csv
  train: train.csv
  target: target
model:
  fold: 5
  params:
    learning_rate: 0.03
    one_hot_max_size: 4
    depth: 4
    eval_metric: F1
    loss_function: Logloss
    iterations: 10000
    cat_features:
    - person_attribute_a_1
    - person_attribute_b
    - person_prefer_c
    - person_prefer_d_1
    - person_prefer_d_2
    - person_prefer_d_3
    - person_prefer_e
    - person_prefer_h_1
    - person_prefer_h_2
    - person_prefer_h_3
    - contents_attribute_i
    - contents_attribute_a
    - contents_attribute_j_1
    - contents_attribute_c
    - contents_attribute_l
    - contents_attribute_d
    - contents_attribute_m
    - contents_attribute_e
    - contents_attribute_h
    - person_rn
    - person_prefer_d_1_attribute_d_d
    - person_prefer_d_1_attribute_d_s
    - person_prefer_d_1_attribute_d_m
    - person_prefer_d_1_attribute_d_l
    - person_prefer_d_2_attribute_d_d
    - person_prefer_d_2_attribute_d_s
    - person_prefer_d_2_attribute_d_m
    - person_prefer_d_2_attribute_d_l
    - person_prefer_d_3_attribute_d_d
    - person_prefer_d_3_attribute_d_s
    - person_prefer_d_3_attribute_d_m
    - person_prefer_d_3_attribute_d_l
    - contents_attribute_d_attribute_d_d
    - contents_attribute_d_attribute_d_s
    - contents_attribute_d_attribute_d_m
    - contents_attribute_d_attribute_d_l
    - person_prefer_h_1_attribute_h_p
    - person_prefer_h_2_attribute_h_p
    - person_prefer_h_3_attribute_h_p
    - contents_attribute_h_attribute_h_p
    - contents_attribute_l_attribute_l_d
    - contents_attribute_l_attribute_l_s
    - contents_attribute_l_attribute_l_m
    - contents_attribute_l_attribute_l_l
  threshold: 0.4
  seed: 42
  verbose: 100
submit:
  name: 5fold_lightgbm.csv
  path: ../submit