hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: ../input/jobcare-recommendation
  submit: sample_submission.csv
  test: test.csv
  train: train.csv
  target: target
experiment:
  project: ds-wook/dacon-project
  tags:
    lightgbm:
    - LightGBM
    - KFold
    - 잡케어 추천
    xgboost:
    - XGBoost
    - KFold
    - 잡케어 추천
model:
  fold: 5
  params:
    learning_rate: 0.023347429226634762
    num_leaves: 51
    max_depth: 6
    subsample: 0.5628109945722505
    colsample_bytree: 0.6331731119758383
    reg_alpha: 0.014180537144799797
    reg_lambda: 0.06467903667112945
    boosting_type: gbdt
    n_estimators: 10000
    n_jobs: -1
    objective: binary
  threshold: 0.35852620618436454
  seed: 42
  verbose: 100
submit:
  name: 5fold_lightgbm.csv
  path: ../submit
