hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: ../input/jobcare-recommendation
  submit: sample_submission.csv
  test: test.csv
  train: train.csv
  target: target
experiment:
  project: ds-wook/dacon-project
  tags:
    lightgbm:
    - LightGBM
    - KFold
    - 잡케어 추천
    xgboost:
    - XGBoost
    - KFold
    - 잡케어 추천
model:
  fold: 5
  params:
    boosting_type: gbdt
    subsample: 0.8
    colsample_bytree: 0.6
    n_estimators: 10000
    n_jobs: -1
    num_leaves: 26
    objective: binary
  threshold: 0.4
  seed: 42
  verbose: 100
submit:
  name: 5fold_lightgbm.csv
  path: ../submit
