hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  cat_features:
  - person_attribute_a_1
  - person_attribute_b
  - person_prefer_c
  - person_prefer_d_1
  - person_prefer_d_2
  - person_prefer_d_3
  - person_prefer_e
  - person_prefer_h_1
  - person_prefer_h_2
  - person_prefer_h_3
  - contents_attribute_i
  - contents_attribute_a
  - contents_attribute_j_1
  - contents_attribute_c
  - contents_attribute_l
  - contents_attribute_d
  - contents_attribute_m
  - contents_attribute_e
  - contents_attribute_h
  - person_prefer_d_1_attribute_d_d
  - person_prefer_d_1_attribute_d_s
  - person_prefer_d_1_attribute_d_m
  - person_prefer_d_1_attribute_d_l
  - person_prefer_d_2_attribute_d_d
  - person_prefer_d_2_attribute_d_s
  - person_prefer_d_2_attribute_d_m
  - person_prefer_d_2_attribute_d_l
  - person_prefer_d_3_attribute_d_d
  - person_prefer_d_3_attribute_d_s
  - person_prefer_d_3_attribute_d_m
  - person_prefer_d_3_attribute_d_l
  - contents_attribute_d_attribute_d_d
  - contents_attribute_d_attribute_d_s
  - contents_attribute_d_attribute_d_m
  - contents_attribute_d_attribute_d_l
  - person_prefer_h_1_attribute_h_m
  - person_prefer_h_1_attribute_h_l
  - person_prefer_h_2_attribute_h_m
  - person_prefer_h_2_attribute_h_l
  - person_prefer_h_3_attribute_h_m
  - person_prefer_h_3_attribute_h_l
  - contents_attribute_h_attribute_h_m
  - contents_attribute_h_attribute_h_l
  - contents_attribute_l_attribute_l_d
  - contents_attribute_l_attribute_l_s
  - contents_attribute_l_attribute_l_m
  - contents_attribute_l_attribute_l_l
  path: ../input/jobcare-recommendation
  submit: sample_submission.csv
  test: test.csv
  train: train.csv
  target: target
experiment:
  project: ds-wook/dacon-project
  tags:
    lightgbm:
    - LightGBM
    - KFold
    - 잡케어
    - Optimization
    xgboost:
    - XGBoost
    - KFold
    - 잡케어
    - Optimization
  trials: 100
  direction: maximize
  params: best_params.yaml
model:
  fold: 5
  threshold: 0.4
  select: lightgbm
  lightgbm:
    params:
      learning_rate:
      - 0.03
      - 0.1
      num_leaves:
      - 4
      - 64
      max_depth:
      - 4
      - 16 
      subsample:
      - 0.1
      - 1.0 
      colsample_bytree:
      - 0.1
      - 1.0 
      reg_alpha:
      - 0.01
      - 0.1 
      reg_lambda:
      - 0.01
      - 0.1
      boosting_type: gbdt
      n_estimators: 10000
      n_jobs: -1
      objective: binary
  