hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: ../input/jobcare-recommendation
  submit: sample_submission.csv
  test: test.csv
  train: train.csv
  target: target
experiment:
  project: ds-wook/dacon-project
  tags:
    lightgbm:
    - LightGBM
    - KFold
    - 잡케어
    - Optimization
    xgboost:
    - XGBoost
    - KFold
    - 잡케어
    - Optimization
  trials: 100
  direction: maximize
  params: best_params.yaml
model:
  fold: 5
  threshold: 0.4
  select: lightgbm
